version: '3'
services:
  server:
    build: Cats_and_Dogs
    ports:
      - "8090:8090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
  alertmanager:
    build: ./alertmanager
    ports:
      - "9093:9093"